version: '2'
services:
  redis:
    image: redis:2.8.17
    volumes:
      - redis-data:/data/
    privileged: true

  database:
    image: postgres:9.5.2
    volumes:
      - psql-data:/var/lib/postgresql/data
    privileged: true
    environment:
      - POSTGRES_DB=hackit
      - POSTGRES_PASSWORD=hackit
      - POSTGRES_USER=hackit

  web:
    build: .
    command: "uwsgi --ini uwsgi.ini --wsgi-file wsgi.py --chdir /srv/"
    ports:
      - 8001:8001
    volumes:
     - .:/srv/
    links:
     - redis:redis
     - database:database
    privileged: true

  celery:
    image: junction_web
    command: celery worker -A junction -l info
    volumes:
     - .:/srv/
    links:
     - redis:redis
     - web:web
     - database:database
    environment:
     - C_FORCE_ROOT=true
volumes:
  redis-data:
    driver: local
  psql-data:
    driver: local
