version: '2'
services:
  redis:
    image: redis:2.8.17
    volumes:
      - redis-data:/data/
    ports:
      - "6380:6379"
    privileged: true

  web:
    build: .
    command: "uwsgi --ini uwsgi.ini  --wsgi-file wsgi.py --chdir /srv/"
    ports:
      - "127.0.0.1:80:80"
    volumes:
     - .:/srv/
    links:
     - redis:redis
    privileged: true

  celery:
    image: junction_web
    command: celery worker -A junction -l info
    volumes:
     - .:/srv/
    links:
     - redis:redis
     - web:web
    environment:
     - C_FORCE_ROOT=true
volumes:
  redis-data:
    driver: local
