version: '2'
services:
  redis:
    image: redis:2.8.17
    volumes:
      - redis-data:/data/
    ports:
      - "6380:6379"
    privileged: true

  web:
    build: .
    command: tail -f /dev/null
    volumes:
     - .:/srv/
    links:
     - redis:redis
    ports:
     - "8000:8000"
    privileged: true

  celery:
    image: junction_web
    command: celery worker -A junction -l info
    volumes:
     - .:/srv/
    links:
     - redis:redis
     - web:web
    environment:
     - C_FORCE_ROOT=true
volumes:
  redis-data:
    driver: local
