# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-12 05:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0025_team_conference'),
        ('proposals', '0024_auto_20170610_1857'),
    ]

    operations = [
    ]
